config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'index', to: 'pages#index'

  resources :appointments

  devise_for :users
  devise_for :doctors, controllers: { registrations: 'doctors/registrations' }
  devise_for :patients, controllers: { registrations: 'patients/registrations' }

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient, class_name: 'Patient'
  belongs_to :doctor, class_name: 'Doctor'

  validates_uniqueness_of :date, scope: [:doctor_id, :patient_id]
  validates_uniqueness_of :hour, scope: [:doctor_id, :patient_id]
  validates_presence_of :date, :hour, :doctor_id, :patient_id
  validates :date, date: {after: Proc.new { Date.today }, message: 'Deve ser maior que a data atual'}
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :appointment_create_access, only: [:create]

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      redirect_to index_path
    else
      render 'appointments/new'
    end
  end

  def index
    if doctor_signed_in?
      @appointments = Appointment.where(doctor_id: current_user.id)
    else
      @appointments = Appointment.where(patient_id: current_user.id)
    end
  end

  def appointment_create_access
    redirect_to appointments_path	if doctor_signed_in?
  end

  private
  def appointment_params
    params.require(:appointment).permit(:patient_id, :doctor_id, :date, :hour)
  end
end

app/views/appointments/index.html.erb
<div class="container text-center">
  <div class="home">
    <h2>Consulta Marcadas</h2>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <% if patient_signed_in? %>
            <th scope="col">Especialidade</th>
          <% end %>
          <th scope="col"><%= doctor_signed_in? ? 'Paciente' : 'Médico' %></th>
          <th scope="col">Data</th>
          <th scope="col">Hora</th>
        </tr>
      </thead>
      <tbody>
      <% @count = 0 %>
      <% @appointments.each do |appointment| %>

        <tr>
          <th scope="row"><%= @count += 1%></th>
          <% if patient_signed_in? %>
            <td> <%= appointment.doctor.expertise %></td>
          <% end %>
          <td> <%= doctor_signed_in? ? appointment.patient.name : appointment.doctor.name %> </td>
          <td> <%= appointment.date.to_formatted_s(:rfc822) %> </td>
          <td> <%= appointment.hour.to_formatted_s(:time) %> </td>
        </tr>
      <% end %>

      </tbody>
    </table>

    <%= link_to "Voltar", :back, class: "btn btn-blue mt-5" %>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="container text-center">
  <div class="home">
    <h2>Marcar Consulta</h2>

    <%= form_with model: @appointment do |f| %>

      <div class="field">
        <%= f.label :'Médico' %><br />
        <%= collection_select(:appointment, :doctor_id, Doctor.where(role: 'doctor').all, :id, :doctor_name_expertise, {:prompt => 'Selecione'} ) %>
      </div>

      <div class="field mt-2">
        <%= f.label :'Data da consulta' %><br />
        <%= f.date_field :date%>
      </div>

      <div class="field mt-2">
        <%= f.label :'Hora da consulta' %><br />
        <%= f.time_field :hour %>
      </div>

      <%= f.hidden_field :patient_id, :value => current_user.id %>

      <%= f.submit 'Marcar', class: "btn btn-purple mt-3" %>
    <% end %>

    <%= link_to "Voltar", :back, class: "btn btn-blue mt-5" %>
  </div>
</div>